### ISSUE TITLE
看了下XSI_msgq的例子

### ISSUE THREAD

**Issue by leopardhope** [clpsz/linux-ipcs#4]
从代码逻辑上看是在父进程中msgget创建了消息队列。

但是fork()之后，如何保证父进程比子进程先执行呢。如果子进程先被调度，会出错。

**Comment by clpsz** [comment]
没有做强制的保证，因为父进程还在运行，而子进行需要等待下一次调度，所以父进程一般会比子进程先执行
这里仅仅是一个例子，所以没有写的特别严谨
